# Numpy

In [2]:
import numpy as np
print("numpy imported successfully")

numpy imported successfully


In [3]:
# to make an array - use np.array() function

a = np.array([[1,2,34],[1,2,34]])
print(a)
print(type(a))

[[ 1  2 34]
 [ 1  2 34]]
<class 'numpy.ndarray'>


In [4]:
#Returns all values as true and 0 as false

n = np.array([1,2,3,4,0],dtype = bool)
print(n)

[ True  True  True  True False]


In [5]:
# np.arange() - returns evenly spaced values within a given interval

print(np.arange(1,10))
print(np.arange(1,10,2))
print(np.arange(11))

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [6]:
#np.reshape() - gives a new shape to an array without changing its data (rows,columns)

arr = np.arange(1,11)
np.reshape(arr,(5,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [7]:
# np.ones() and np.zeros() - returns a new array of given shape and type, filled with ones or zeros

print(np.ones((3,4),dtype = int))
print(np.zeros((3,4),dtype = int))

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [8]:
# np.random() - returns an array of random numbers

np.random.random((3,4))

array([[0.48337812, 0.46231364, 0.66065553, 0.364751  ],
       [0.06400052, 0.65097237, 0.74747228, 0.68820726],
       [0.68817017, 0.74388952, 0.37990225, 0.74981421]])

In [9]:
# np.linspace() - returns evenly spaced numbers over a specified interval

np.linspace(-10,10,10)

#what this does is it returns 10 evenly spaced numbers from -10 to 10. The first two arguments are the start and end values, and the third argument is the number of evenly spaced samples to generate.

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [10]:
# np.identity() - returns a square array with ones on the diagonal and zeros elsewhere

np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
a1 = np.arange(10)
a2 = np.arange(12,dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

## Features of an array

In [12]:
# ndim - gives the number of dimensions of the array

print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [13]:
# shape - gives the shape of the array

print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [14]:
# size - gives the total number of elements in the array

print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [15]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


In [16]:
# astype() - returns an array with the same data but a new data type

print(a1.dtype)

int64


In [17]:
a1 = a1.astype(np.int32)
print(a1.dtype)

int32


In [18]:
a = np.arange(1,13).reshape(3,4)
b = np.arange(13,25).reshape(3,4)

print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [19]:
# Scalar operations - operations that are performed on each element of the array

print(a)
print(a*2)
print(a + 5)

#Here any operation performed on an array is applied to each element of the array. This is called broadcasting.

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
[[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]


In [20]:
# Relational operators - returns a boolean array

print(b)
print(b > 18)
print(b <= 20)

# Here the boolean operators are applied to each element of the array and return a boolean array of the same shape as the original array.

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[[ True  True  True  True]
 [ True  True  True  True]
 [False False False False]]


In [21]:
#Vector operations - operations that are performed on two arrays of the same shape

print(a,"\n\n",b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

 [[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [22]:
print(a + b)
print(a * b)

# Here the vector operations are applied to the corresponding elements of the two arrays and return a new array of the same shape as the original arrays.

[[14 16 18 20]
 [22 24 26 28]
 [30 32 34 36]]
[[ 13  28  45  64]
 [ 85 108 133 160]
 [189 220 253 288]]


In [23]:
ran = np.random.random((3,3))
ran = np.round(ran*100)
ran

array([[82., 21., 84.],
       [57., 38., 13.],
       [16., 92., 93.]])

In [24]:
# Some functions you can use in an array

print(np.max(ran))
print(np.min(ran))
print(np.sum(ran))
print(np.prod(ran))

93.0
13.0
496.0
557577186776064.0


In [25]:
#we can use the axis parameter to specify the axis along which to perform the operation. For example, if we want to find the maximum value of each column, we can use axis=0. If we want to find the maximum value of each row, we can use axis=1.

print(np.max(ran,axis = 0)) # returns the maximum value of each column
print(np.max(ran,axis = 1)) # returns the maximum value of each row

[82. 92. 93.]
[84. 57. 93.]


In [26]:
#Statistical functions - returns the mean, median, standard deviation and variance of the array

print(np.mean(ran)) #gives expected value of the array
print(np.median(ran)) #returns the median value of the array
print(np.std(ran)) # returns the standard deviation of the array
print(np.var(ran)) # returns the variance of the array

55.111111111111114
57.0
31.82746697934015
1012.9876543209876


In [27]:
# Dot product - returns the dot product of two arrays

c = np.arange(12).reshape(4,3)
print(np.dot(a,c)) # returns the dot product of a and b

# for the dot product to be defined, the number of columns in the first array must be equal to the number of rows in the second array. In this case, a has 4 columns and c has 4 rows, so the dot product is defined and returns a new array with shape (3,3).

[[ 60  70  80]
 [132 158 184]
 [204 246 288]]


In [28]:
# round function is used to round off the value to the neaest integer.

roun = np.random.random((3,3))
print(roun,"\n")

roun = np.round(roun*100)
print(roun)

[[0.79769703 0.76929504 0.23476124]
 [0.58909515 0.63435906 0.5175034 ]
 [0.64000625 0.52943619 0.65402874]] 

[[80. 77. 23.]
 [59. 63. 52.]
 [64. 53. 65.]]


In [29]:
#floor - throws the integer value of the number. It returns the largest integer less than or equal to the input value.
print(np.floor(roun))

# using floor - 5.9 will never go to 6, it will always go to 5.0. It is used to round down the value to the neareest integer.

[[80. 77. 23.]
 [59. 63. 52.]
 [64. 53. 65.]]


In [30]:
# ceil - throws the integer value of the number. It returns the smallest integer greater than or equal to the input value.
print(np.ceil(roun))

# using ceil - 2.1 will always round up to 3.0. It is used to round up the value to the nearest integer.

[[80. 77. 23.]
 [59. 63. 52.]
 [64. 53. 65.]]


## Indexing and Slicing

In [31]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(27).reshape(3,3,3)

In [32]:
print(a1)
a1[-1] # returns the last element of the array

[0 1 2 3 4 5 6 7 8 9]


np.int64(9)

In [33]:
print(a2)
a2[1,2] # [row,column] - starting from 0,0. So 1,2 means 2nd row and 3rd column. It will return the value at that position.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


np.int64(6)

In [34]:
print (a3)
a3[1,1,0]  # [matrix,row,column] - starting from 0,0,0. So 1,1,0 means 2nd matrix, 2nd row and 1st column. It will return the value at that position.

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


np.int64(12)

In [35]:
a1[0:4] # returns the first 4 elements of the array

array([0, 1, 2, 3])

In [36]:
print(a2)
print(a2[:,2])
print(a2[0:3,0:1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 2  6 10]
[[0]
 [4]
 [8]]


In [37]:
a2[::2, ::3]

array([[ 0,  3],
       [ 8, 11]])

In [38]:
a2[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [39]:
a2[0:2,1:] 

array([[1, 2, 3],
       [5, 6, 7]])

In [40]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [41]:
a3[0,1]

array([3, 4, 5])

In [42]:
a3[1,:,1]

array([10, 13, 16])

In [43]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [44]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [45]:
for i in a2:
    print(i)

    # it prints row by row. So first it will print the first row, then the second row and then the third row.

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [46]:
for i in a3:
    print(i)

    # prints matrix by matrix. So first it will print the first matrix, then the second matrix and then the third matrix.

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


## iter

In [47]:
for i in np.nditer(a2):
    print(i)

    # prints element by element. So first it will print the first element, then the second element and so on.

0
1
2
3
4
5
6
7
8
9
10
11


In [48]:
for i in np.nditer(a3):
    print(i)

    # prints element by element. So first it will print the first element, then the second element and so on.

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [49]:
# Transpose - returns a view of the array with axes transposed

print(a2)
print(a2.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [50]:
# ravel - returns a flattened array

print(a2)
print(a2.ravel())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


### Stacking of arrays

In [51]:
# Horizontal stacking - stacks arrays in sequence horizontally (column wise)

a = np.arange(1,13).reshape(3,4)
b = np.arange(13,25).reshape(3,4)
print(np.hstack((a,b)))

[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]


In [52]:
# Vertical stacking - stacks arrays in sequence vertically (row wise)

print(np.vstack((a,b)))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


### Splitting of array

In [60]:
# Horizontal split - splits an array into multiple sub-arrays horizontally (column wise)

print(a2)
print(np.hsplit(a2,4)) # splits the array into 2 sub-arrays

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [ ]:
# Vertical split - splits an array into multiple sub-arrays vertically (row wise)

print(np.vsplit(a2,3)) # splits the array into 3 sub-arrays

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
